#!/bin/bash
# bladder:
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/bladder/s0962_urinary_bladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/bladder/s0265_urinary_bladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/bladder/s0209_urinary_bladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/bladder/s1063_urinary_bladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/bladder/s0283_urinary_bladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/bladder/s0640_urinary_bladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/bladder/s0938_urinary_bladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/bladder/s0679_urinary_bladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/bladder/s1246_urinary_bladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/bladder/s0122_urinary_bladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/bladder/s0383_urinary_bladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/bladder/s0462_urinary_bladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/bladder/s1206_urinary_bladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/bladder/s0656_urinary_bladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/bladder/s0009_urinary_bladder*
# colon:
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0935_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0987_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0067_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0718_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0469_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0231_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1220_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0829_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0296_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0840_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1101_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0695_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0465_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0439_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1179_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1084_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0299_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0199_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0995_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0088_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0389_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0977_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0247_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0941_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0373_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1134_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0901_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1079_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0262_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0438_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0738_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0223_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0989_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1225_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0805_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0457_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0313_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1173_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0215_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1243_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0958_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1106_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0710_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0422_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0793_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0908_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1146_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0780_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0891_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0488_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1035_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0604_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1133_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0821_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0672_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1203_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0736_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0132_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1017_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0338_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0850_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0808_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1060_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0781_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0354_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0364_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1190_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0826_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0659_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0654_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1096_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0424_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0700_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0897_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0444_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0783_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0681_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0265_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0676_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0811_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0608_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0374_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0750_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0165_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1104_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0398_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0844_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0795_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1191_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1270_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0773_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0999_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0380_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0825_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0376_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0798_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1042_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0714_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0233_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0046_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0443_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0775_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0039_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0741_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1039_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0645_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0360_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0633_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1201_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0729_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0285_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0270_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0834_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0122_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0420_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1067_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0367_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0717_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1119_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0832_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s1271_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0531_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0209_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0771_colon*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/colon/s0114_colon*
# coronary_artery_left:
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/11986246_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12040322_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12060183_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/11986477_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/11621690_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/11297515_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12062410_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/10649241_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/11920334_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12019477_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12073201_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/10996654_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12080096_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12061306_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12070433_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/11963813_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/10312291_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/10371282_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/11986246_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12017096_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12063606_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/10346727_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/10868982_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/11995079_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12025460_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12076476_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/10175956_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/10367641_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/10565389_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/11149298_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/11181465_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/11187940_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/11737078_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/11866344_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/11980350_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/11984870_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12014707_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12016636_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12017895_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12018389_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12019951_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12058223_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12058606_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12061006_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12067976_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12070494_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12077776_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12078193_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12082402_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12084143_0*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_left/12078094_0*
# coronary_artery_right:
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/10868982_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12076716_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/11981723_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/10115848_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12080930_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/11777150_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12076476_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/11354834_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12069007_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/10312291_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/10371282_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/11986246_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12017096_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12063606_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/10346727_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/10868982_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/11995079_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12025460_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12076476_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/10175956_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/10367641_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/10565389_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/11149298_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/11181465_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/11187940_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/11737078_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/11866344_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/11980350_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/11984870_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12014707_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12016636_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12017895_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12018389_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12019951_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12058223_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12058606_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12061006_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12067976_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12070494_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12077776_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12078193_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12082402_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12084143_1*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/coronary_artery_right/12078094_1*
#duodenum:
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0381_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0640_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1096_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0470_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0847_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0331_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0808_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0385_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0322_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0659_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0303_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0386_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0834_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0506_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0898_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1079_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0897_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0413_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0785_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0679_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1125_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0724_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1060_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0658_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0046_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0676_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0565_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0237_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0810_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0420_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0299_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0376_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0364_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0976_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0463_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0455_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0138_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0632_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0647_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0910_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0833_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0753_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1057_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1050_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1101_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0735_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0469_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0816_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0774_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1271_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0218_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0800_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0012_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0954_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0606_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1098_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0795_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0262_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0398_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0498_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0696_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0088_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0866_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/065884_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0039_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0890_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0211_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0160_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0522_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0845_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0459_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0508_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0889_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0729_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0165_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0907_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0520_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0104_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1173_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0618_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1073_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0951_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1041_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0253_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0433_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0488_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0393_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1245_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0438_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0718_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0490_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0908_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0975_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0698_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0510_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0821_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0978_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0704_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0789_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0246_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0930_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0129_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0301_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0580_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0743_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0784_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0822_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0380_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0771_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0111_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0641_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0454_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0156_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0216_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1162_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0102_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0439_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1269_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0430_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0915_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0452_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0719_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0598_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0266_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0941_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1052_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0139_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1270_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0770_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1255_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0357_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1140_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1256_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0209_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0265_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1272_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0688_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0240_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1144_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0365_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0573_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0264_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1223_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0664_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0776_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1151_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1199_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1119_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1066_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1023_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0422_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0557_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1157_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0080_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1164_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1136_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1155_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0245_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0747_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0531_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1132_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0247_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0482_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1158_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0485_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s0305_duodenum*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/duodenum/s1176_duodenum*
# gallbladder:
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0376_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0773_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/047863_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0077_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0237_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1152_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0421_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1191_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0354_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0658_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0785_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0798_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/096698_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0331_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0584_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0111_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0632_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0463_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0833_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0191_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0402_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1271_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0233_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1225_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0016_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0805_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0700_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0775_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1151_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0810_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1105_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0132_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1101_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0698_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0897_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1067_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0899_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0536_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0407_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0753_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1178_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1048_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0973_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0952_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0470_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1173_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1096_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0910_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1060_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0102_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0211_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0565_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/041469_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0914_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0258_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0747_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/097036_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0096_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0235_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1167_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0659_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/042071_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0046_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1165_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0459_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0455_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0171_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0250_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1140_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/054309_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0462_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0447_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1187_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1073_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0664_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/008738_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0719_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1146_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1162_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/086763_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0606_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/027527_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1164_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0469_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0716_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0923_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0253_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0674_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0349_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0765_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0880_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0371_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1183_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1264_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0339_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0890_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0676_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0615_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0834_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/046988_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0795_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/080269_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0009_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0488_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0509_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0088_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1132_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0039_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0975_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0438_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0618_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1245_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0498_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0138_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0242_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0257_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0531_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0585_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1158_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/014836_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0959_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0961_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0945_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1058_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0898_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0957_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0433_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0737_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0028_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0816_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0413_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/053966_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0059_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1110_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1143_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0248_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1031_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0227_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0592_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0767_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/095123_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0688_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s1008_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0771_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0510_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0320_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/046343_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0490_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0508_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/009129_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0529_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0266_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0213_gallbladder*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/gallbladder/s0322_gallbladder*
# liver:
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0981_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0724_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0951_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1050_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0381_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0646_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1041_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0907_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0399_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0219_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0774_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0062_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0083_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1151_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0573_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0084_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0368_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0233_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1048_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1136_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1256_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0216_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0987_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0105_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0693_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0353_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0424_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0883_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0684_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0846_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0679_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1137_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0129_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0361_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0067_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1197_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0581_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1250_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0335_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0655_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1097_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1025_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1134_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0382_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1251_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0313_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0980_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0740_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0858_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0936_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1026_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0881_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0652_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0879_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0838_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0852_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1049_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0386_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0356_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0791_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0595_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0996_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1106_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0738_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0347_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1021_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0935_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0528_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0876_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0647_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1239_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0972_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0175_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1237_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0825_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0901_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0782_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0891_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1084_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0009_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0877_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1243_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0839_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0956_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0391_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0221_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0671_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0579_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1258_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0209_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0911_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1033_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1182_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0085_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1259_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0676_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0813_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1179_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1122_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0700_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0532_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0465_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1254_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0697_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0191_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1002_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0389_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0265_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0188_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0826_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1203_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0068_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0736_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0848_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0958_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0977_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0608_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0520_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1225_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1165_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0376_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0246_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1004_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0952_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0767_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0840_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0283_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0261_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0594_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0832_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0710_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0695_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0780_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0237_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s1226_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0336_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0691_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0584_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0405_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0034_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0750_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0377_liver*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/liver/s0373_liver*
# pancreas:
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0717_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0829_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1179_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0659_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0386_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1136_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0891_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0413_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1151_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0399_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0787_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0215_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0414_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0246_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0230_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0310_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1083_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1225_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0032_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0793_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0270_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1251_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0128_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1048_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0444_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0973_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1256_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0750_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0805_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0437_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0832_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0223_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1109_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0459_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0398_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0976_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0672_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0249_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0668_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0811_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0679_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0285_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0378_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0184_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0759_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0693_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0364_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0581_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0517_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1033_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0420_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0088_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0890_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0367_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0221_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0199_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0598_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1201_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1190_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0780_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0688_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0700_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0714_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0363_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0037_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0582_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1094_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0775_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0376_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0438_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1146_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0455_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0676_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0515_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0698_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0844_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0487_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0647_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0821_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0810_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0654_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1133_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0544_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0952_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0604_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0425_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1101_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0306_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1060_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1039_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1172_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0211_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1079_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0753_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1042_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0353_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0658_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0910_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0795_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0261_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0664_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0871_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0808_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0331_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1164_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1173_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0847_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0770_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1017_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0374_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0898_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0696_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0579_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0897_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1271_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0102_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0380_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0584_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0490_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0012_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0798_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1069_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0313_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0880_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0470_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1052_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0156_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s1191_pancreas*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/pancreas/s0262_pancreas*
# spleen:
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1109_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0782_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0848_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1251_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0368_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0980_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0879_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0676_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0084_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1097_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1203_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0476_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0313_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1048_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0858_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0175_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0936_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0738_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0386_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1250_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0697_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0952_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1025_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0671_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0838_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0356_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0881_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0852_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1243_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0233_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1021_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0655_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0068_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1225_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0347_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0877_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0911_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1182_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1106_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0532_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0736_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0520_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0377_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0700_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1134_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0876_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0996_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0009_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0958_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0956_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0839_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0391_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1017_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0335_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0595_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1254_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1002_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1026_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1197_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0283_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0191_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0988_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0261_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1004_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0935_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0083_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0105_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0647_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0465_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0389_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0445_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0584_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0840_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0594_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0901_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0299_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0987_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0710_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0421_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1252_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0032_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0482_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0767_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0973_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1259_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0773_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1122_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0831_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0813_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0791_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0977_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0528_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0787_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0916_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0444_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0364_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0006_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0788_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1226_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1236_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1206_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0457_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1165_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0750_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0424_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0376_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0310_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1179_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0672_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0357_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0670_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0939_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0798_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0414_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0605_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0890_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0659_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1175_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0405_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0891_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1094_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0336_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0146_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1146_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0338_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0717_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0961_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0825_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0494_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0690_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0206_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1039_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0802_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1212_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1088_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1083_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0247_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1085_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0649_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0241_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0249_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0989_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0871_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0836_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0579_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s1144_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0793_spleen*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/spleen/s0708_spleen*
# stomach:
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0883_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0712_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0838_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1049_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0879_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0693_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0781_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1203_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0595_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0782_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0368_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0246_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0175_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0313_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0528_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1197_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0996_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0581_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1250_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1258_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0936_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0697_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1084_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1026_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0676_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0454_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0356_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0335_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0233_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0353_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0901_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0972_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1021_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0655_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0740_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1097_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1243_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0083_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0386_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0956_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0679_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0793_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0958_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0876_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1182_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0935_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0391_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0373_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0520_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0594_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0813_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0347_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0336_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1017_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0788_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0009_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0839_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0980_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0209_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1136_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0647_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1134_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0858_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1004_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1179_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0092_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0509_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0767_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0738_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0068_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0952_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0710_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1254_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0785_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0881_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0791_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0995_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0221_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1226_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0877_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0987_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1175_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0798_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0700_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0891_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0129_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1248_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0759_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0465_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0608_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0582_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0261_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0829_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0188_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0331_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0389_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0579_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0128_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0283_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0085_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0911_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0285_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0977_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0039_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0915_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1039_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0006_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0530_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1094_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0832_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0840_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0690_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0584_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0459_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0032_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0681_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1259_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1165_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0294_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0605_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0780_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0682_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0735_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0231_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0805_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1002_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0671_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0871_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0566_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0773_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0973_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0895_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1172_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1271_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0989_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0358_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0157_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0890_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0354_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0750_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0532_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0363_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1236_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0908_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0691_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s1146_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0179_stomach*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/stomach/s0338_stomach*
# trachea:
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0956_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0106_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0744_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0996_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0057_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0270_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0665_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s1250_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0505_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0356_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0368_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s1149_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0782_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0848_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0568_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s1084_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s1106_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0217_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0638_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0100_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0043_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0767_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0282_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0870_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0843_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0563_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0655_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0299_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0391_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0259_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s1168_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0295_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0710_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0953_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0003_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s1051_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0876_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0832_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0140_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0025_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0234_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0002_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0980_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0085_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0219_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0781_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0955_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0359_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0208_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0851_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s1218_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0532_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0875_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0396_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s1185_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0395_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0642_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s1112_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0056_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0453_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0594_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s1222_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0715_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0791_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0278_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0493_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s1071_trachea*
rm /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/*/trachea/s0312_trachea*