# train ae or vae
mode: test
model:
  name: DDIM
  num_steps: 1000
  beta_schedule: consine
  eps_model:
    name: Base
    # encoder config
    time_channel: 128
    encoder:
      name: UNet
      image_size: [28, 28]
      in_channel: 3
      patch_size: 1
      down_channels: [128, 256]
      middle_channels: [512, 512]
      ## allow an asummetrical architecture
      # decode_down_channels: [32, 64]
      ### with time embedding
      building_block: res
      activation: silu
      num_blocks: 2
      normalization: group
      num_norm_groups: 16
      dropout: 0.1
      ## the value can be list or int
    condition_embedding:
      combine_condition: add
      merge_timestep_and_condition: true
      encoder:
        name: OneHot
        type: categories
        out_channel: 128
        num_classes: 10
  classifier_free_guidance:
    condition_dropout: 0.2
    guidance_weight: 2.0
model_path: /media/wlsdzyzl/DATA1/flemme-ckp/CIFAR10/CDDPM/ckp_last.pth
loader:
  dataset: 
    name: CIFAR10
    data_path: /media/wlsdzyzl/DATA1/datasets/CIFAR10
  batch_size: 64
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Resize
      ## the value must be list
      size: [28, 28]
    - name: ToTensor
    - name: Normalize
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
eval_batch_num: 1
recon_dir: /media/wlsdzyzl/DATA1/flemme-results/recon/cifar10/cddim
eval_gen:
  gen_dir: /media/wlsdzyzl/DATA1/flemme-results/gen/cifar10/cddim
  sampler:
    name: NormalSampler
    rand_seed: 2024
    clipped: true
    clip_range: [-1.0, 1.0]
  random_sample_num: 100
