# train ae or vae
mode: test
model:
  # can be AE, VAE and DDPM
  name: SDM
  diffusion:
    name: EDM
    num_ensemble: 1
    # encoder config
    eps_model:
        # encoder config
      time_channel: 128
      encoder:
        name: UNet
        image_size: [320, 320]
        in_channel: 1
        out_channel: 1
        patch_channel: 32
        patch_size: 2
        # kernel_size: 5
        down_channels: [64, 128, 256]
        middle_channels: [512, 512]
        ### with time embedding
        building_block: single
        activation: silu
        num_blocks: 2
        normalization: group
        num_norm_groups: 16
        dropout: 0.1
      condition_embedding:
        combine_condition: cat
        encoder:
          name: Identity
          out_channel: 1
    ### loss function
    eps_loss:
      name: MSE
loader:
  dataset: 
    name: ImgReconDataset
    data_dir: mzf1
    target_dir: esc
    data_suffix: png
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/img/fastMRI/knee_single/png/fold5/
  batch_size: 16
  num_workers: 8
  shuffle: true
  data_transforms:
    # - name: Resize
    #   ## the value must be list
    #   size: [320, 320]
    - name: ToTensor
    - name: Normalize
      mean: [0.5]
      std: [0.5]
  target_transforms:
    - name: ToTensor
    - name: Normalize
      mean: [0.5]
      std: [0.5]

model_path: /media/wlsdzyzl/DATA/flemme-ckp/fastMRI-mzf1/UNet_SDM/ckp_last.pth
recon_dir: /media/wlsdzyzl/DATA/flemme-results/recon/fastMRI-mzf1/UNet_SDM/
save_target: true
save_input: true
evaluation_metrics:
  recon:
    - name: SSIM
      data_range: 2.0
    - name: PSNR
      data_range: 2.0
    - name: MSE

eval_gen:
  gen_dir: /media/wlsdzyzl/DATA/flemme-results/gen/fastMRI-mzf1/UNet_SDM/
eval_batch_num: 1