# train ae or vae
mode: train
model:
  # can be AE, VAE and DDPM
  name: HAE
  is_supervised: true
  # encoder config
  encoder:
    name: VMambaU
    image_size: [320, 320]
    in_channel: 1
    out_channel: 1
    patch_channel: 32
    patch_size: 2
    down_channels: [64, 128, 256]
    middle_channels: [512, 512]
    building_block: vmamba
    normalization: layer
    scan_mode: single
    flip_scan: false
  ### loss function
  reconstruction_losses: 
    - name: L1
loader:
  dataset: 
    name: ImgSegDataset
    data_dir: mzf1
    label_dir: esc
    data_suffix: png
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/fastMRI/knee_single/png/fold1/
    - /media/wlsdzyzl/DATA/datasets/fastMRI/knee_single/png/fold2/
    - /media/wlsdzyzl/DATA/datasets/fastMRI/knee_single/png/fold3/
  batch_size: 8
  num_workers: 8
  shuffle: true
  data_transforms:
    # - name: Resize
    #   ## the value must be list
    #   size: [320, 320]
    - name: ToTensor
    - name: Normalize
      mean: [0.5]
      std: [0.5]
  label_transforms:
    - name: ToTensor
    - name: Normalize
      mean: [0.5]
      std: [0.5]
val_loader:
  dataset: 
    name: ImgSegDataset
    data_dir: mzf1
    label_dir: esc
    data_suffix: png
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/fastMRI/knee_single/png/fold4/
  batch_size: 8
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: ToTensor
    - name: Normalize
      mean: [0.5]
      std: [0.5]
  label_transforms:
    - name: ToTensor
    - name: Normalize
      mean: [0.5]
      std: [0.5]
check_point_dir: /media/wlsdzyzl/DATA/flemme-ckp/fastMRI-mzf1/MambaU_HAE
# resume: /media/wlsdzyzl/DATA/flemme-ckp/fastMRI-mzf1/MambaU_HAE/ckp_last.pth
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0003
  weight_decay: 0.00000001
lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
evaluation_metrics:
  recon:
    - name: SSIM
      data_range: 2.0
    - name: PSNR
      data_range: 2.0
    - name: MSE
score_metric:
  name: SSIM
  higher_is_better: true
max_epoch: 50
warmup_epochs: 1
write_after_iters: 50
save_after_epochs: 1