# train ae or vae
mode: train
model:
  # can be AE, VAE and DDPM
  name: HAE
  is_supervising: true
  # encoder config
  encoder:
    name: CNN
    image_size: [320, 320]
    in_channel: 1
    out_channel: 1
    patch_channel: 32
    patch_size: 2
    # kernel_size: 5
    down_channels: [64, 128, 256]
    middle_channels: [512, 512]
    building_block: res
    num_block: 1
    normalization: batch
    activation: relu
    abs_pos_embedding: false
  ### loss function
  reconstruction_losses: 
    - name: L1
loader:
  dataset: 
    name: ImgSegDataset
    data_dir: mzf1
    label_dir: esc
    data_suffix: png
  data_path_list: 
    - path/to/datasets/fastMRI/knee_single_png/fold1/
    - path/to/datasets/fastMRI/knee_single_png/fold2/
    - path/to/datasets/fastMRI/knee_single_png/fold3/
  batch_size: 16
  num_workers: 8
  shuffle: true
  data_transforms:
    # - name: Resize
    #   ## the value must be list
    #   size: [320, 320]
    - name: ToTensor
    - name: Normalize
      mean: [0.5]
      std: [0.5]
  label_transforms:
    - name: ToTensor
    - name: Normalize
      mean: [0.5]
      std: [0.5]
val_loader:
  dataset: 
    name: ImgSegDataset
    data_dir: mzf1
    label_dir: esc
    data_suffix: png
  data_path_list: 
    - path/to/datasets/fastMRI/knee_single_png/fold4/
  batch_size: 8
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: ToTensor
    - name: Normalize
      mean: [0.5]
      std: [0.5]
  label_transforms:
    - name: ToTensor
    - name: Normalize
      mean: [0.5]
      std: [0.5]
check_point_dir: path/to/checkpoint/fastMRI-mzf1/ResNet_HAE

### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0003
  weight_decay: 0.00000001
lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
evaluation_metrics:
  recon:
    - name: SSIM
      data_range: 2.0
    - name: PSNR
      data_range: 2.0
    - name: MSE
score_metric:
  name: SSIM
  higher_is_better: true
max_epoch: 50
warmup_epoch: 1
write_after_iters: 50
save_after_epochs: 1