# train ae or vae
#### a template for pcd encoder
mode: test
determinstic: True
model:
  # can be AE, VAE, SeM and DDPM
  name: SeM
  # encoder config
  encoder:
    name: PointNet2
    in_channel: 3
    out_channel: 46
    point_num: 4096
    building_block: dense
    # num_neighbors_k: 20
    num_neighbors_k: 32
    num_fps_points: [2048, 1024, 512, 256, 128]
    neighbor_radius: [0.1, 0.2, 0.4, 0.6, 0.8]
    fps_feature_channels: [64, 64, 128, 256, 512]
    fp_channels: [512, 512, 256, 256, 128]
    dense_channels: [1024]
    activation: lrelu
    normalization: group
    vector_embedding: False
  segmentation_losses:
    - name: Dice
      normalization: softmax
    - name: CE
loader:
  dataset: 
    name: PcdSegDataset
    data_dir: pcd
    label_dir: coarse_label
    data_suffix: .ply
    label_suffix: .seg
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/pcd/MedPointS/segmentation/fold5
  batch_size: 16
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 4096
    - name: ToTensor
  label_transforms:
    - name: FixedPoints
      num: 4096
    - name: Relabel
      offset: -1
    - name: ToOneHot
      num_classes: 46
    - name: ToTensor

model_path: /media/wlsdzyzl/DATA/flemme-ckp/MedPointS/PointNet2/PointNet2_SEG_WO_Dense/ckp_best_loss.pth
seg_dir: /media/wlsdzyzl/DATA/flemme-results/seg/medshapenet/PointNet2/
save_colorized: true
save_target: true
evaluation_metrics:
  seg:
    - name: mIoU
    - name: Dice
    - name: SoftDice
