# train ae or vae
#### a template for pcd encoder
mode: train
model:
  # can be AE, VAE, SeM and DDPM
  name: SeM
  # encoder config
  encoder:
    name: PointTrans2
    in_channel: 3
    out_channel: 46
    point_num: 4096
    building_block: pct_oa
    num_neighbors_k: 32
    num_fps_points: [2048, 1024, 512, 256, 128]
    fps_feature_channels: [64, 64, 128, 256, 512]
    neighbor_radius: [0.1, 0.2, 0.4, 0.6, 0.8]
    fp_channels: [512, 512, 256, 256, 128]
    dense_channels: [1024]
    activation: lrelu
    normalization: group
    # long_range_modeling: True
    # pos_embedding: True
  segmentation_losses:
    - name: Dice
      normalization: softmax
    - name: CE
loader:
  dataset: 
    name: PcdSegDataset
    data_dir: pcd
    label_dir: coarse_label
    data_suffix: .ply
    label_suffix: .seg
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/pcd/MedPointS/segmentation/fold1
    - /media/wlsdzyzl/DATA/datasets/pcd/MedPointS/segmentation/fold2
    - /media/wlsdzyzl/DATA/datasets/pcd/MedPointS/segmentation/fold3
  batch_size: 16
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 4096
    - name: ToTensor
  label_transforms:
    - name: FixedPoints
      num: 4096
    - name: Relabel
      offset: -1
    - name: ToOneHot
      num_classes: 46
    - name: ToTensor
val_loader:
  dataset: 
    name: PcdSegDataset
    data_dir: pcd
    label_dir: coarse_label
    data_suffix: .ply
    label_suffix: .seg
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/pcd/MedPointS/segmentation/fold4
  batch_size: 8
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 4096
    - name: ToTensor
  label_transforms:
    - name: FixedPoints
      num: 4096
    - name: Relabel
      offset: -1
    - name: ToOneHot
      num_classes: 46
    - name: ToTensor
check_point_dir: /media/wlsdzyzl/DATA/flemme-ckp/MedPointS/PointTrans2/PointTrans2_SEG
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.00000001
evaluation_metrics:
  seg:
    - name: mIoU
score_metric:
  name: mIoU
### scheduler for learning rate
lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
max_epoch: 200
write_after_iters: 20
save_after_epochs: 2
