# train ae or vae
#### a template for pcd encoder
mode: train
model:
  # can be AE, VAE, SeM and DDPM
  name: SeM
  # encoder config
  encoder:
    name: PointNet2
    in_channel: 3
    out_channel: 46
    point_num: 4096
    building_block: dense
    # num_neighbors_k: 20
    num_neighbors_k: 32
    num_fps_points: [2048, 1024, 512, 256, 128]
    neighbor_radius: [0.1, 0.2, 0.4, 0.6, 0.8]
    fps_feature_channels: [64, 64, 128, 256, 512]
    # voxel_resolutions: [32, 32, 16, 8, 4]
    fp_channels: [512, 512, 256, 256, 128]
    dense_channels: [1024]
    activation: lrelu
    normalization: group
    vector_embedding: False
  segmentation_losses:
    - name: Dice
      normalization: softmax
    - name: CE
loader:
  dataset: 
    name: PcdSegDataset
    data_dir: pcd
    label_dir: coarse_label
    data_suffix: .ply
    label_suffix: .seg
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/pcd/MedPointS/segmentation/fold1
    - /media/wlsdzyzl/DATA1/datasets/pcd/MedPointS/segmentation/fold2
    - /media/wlsdzyzl/DATA1/datasets/pcd/MedPointS/segmentation/fold3
  batch_size: 8
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 4096
    - name: ToTensor
      dtype: float
  label_transforms:
    - name: FixedPoints
      num: 4096
    - name: ToOneHot
      num_classes: 47
      ignore_background: true
    - name: ToTensor
      dtype: float
val_loader:
  dataset: 
    name: PcdSegDataset
    data_dir: pcd
    label_dir: coarse_label
    data_suffix: .ply
    label_suffix: .seg
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/pcd/MedPointS/segmentation/fold4
  batch_size: 32
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 4096
    - name: ToTensor
      dtype: float
  label_transforms:
    - name: FixedPoints
      num: 4096
    - name: ToOneHot
      num_classes: 47
      ignore_background: true
    - name: ToTensor
      dtype: float
check_point_dir: /media/wlsdzyzl/DATA1/flemme-ckp/MedPointS/PointNet2/PointNet2_SEG_WO_Dense
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.00000001
evaluation_metrics:
  seg:
    - name: mIoU
score_metric:
  name: mIoU
### scheduler for learning rate
lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
max_epoch: 200
write_after_iters: 20
save_after_epochs: 2
