loader:
  dataset: 
    name: PcdReconWithClassLabelDataset
    data_dir: partial
    target_dir: target
    data_suffix: .ply
    target_suffix: .ply
    cls_label: MedPointS
  data_path_list: 
    - /data/guoqingzhang/datasets/MedPointS/completion/fold1
    - /data/guoqingzhang/datasets/MedPointS/completion/fold2
    - /data/guoqingzhang/datasets/MedPointS/completion/fold3
    - /data/guoqingzhang/datasets/MedPointS/completion/fold4
    - /data/guoqingzhang/datasets/MedPointS/completion/fold5
  batch_size: 128
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 2048
    - name: ToTensor
  target_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 2048
    - name: ToTensor
  label_transforms:
    - name: Relabel
      offset: -1
    - name: ToOneHot
      num_classes: 46
    - name: ToTensor