loader:
  dataset: 
    name: PcdSegDataset
    data_dir: pcd
    label_dir: coarse_label
    data_suffix: .ply
    label_suffix: .seg
  data_path_list: 
    - /data/guoqingzhang/datasets/MedPointS/segmentation/fold1
    - /data/guoqingzhang/datasets/MedPointS/segmentation/fold2
    - /data/guoqingzhang/datasets/MedPointS/segmentation/fold3
    - /data/guoqingzhang/datasets/MedPointS/segmentation/fold4
    - /data/guoqingzhang/datasets/MedPointS/segmentation/fold5
  batch_size: 32
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 4096
    - name: ToTensor
  label_transforms:
    - name: FixedPoints
      num: 4096
    - name: Relabel
      offset: -1
    - name: ToOneHot
      num_classes: 46
    - name: ToTensor