# train ae or vae
mode: test
model:
  # can be AE, VAE and DDPM
  name: HSeM
  # encoder config
  encoder:
    name: CNN
    image_size: [256, 256]
    in_channel: 1
    out_channel: 1
    proj_channel: 32
    proj_scaling: 2
    down_channels: [64, 128, 256]
    middle_channels: [512, 512]
    building_block: res
    num_block: 1
    normalization: batch
  ### loss function
  segmentation_losses: 
    - name: Dice
    - name: BCEL
  # some other information related to the model
  # in ddpm, it can be the time steps and so on.
loader:
  dataset: 
    name: ImgSegDataset
    data_suffix: jpg
    data_dir: image
    label_dir: mask
  data_path_list: 
    - path/to/datasets/thyroid/tn3k/fold5/
  batch_size: 4
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: Resize
      ## the value must be list
      size: [256, 256]
    - name: ToTensor
  label_transforms:
    - name: Resize
      ## the value must be list
      size: [256, 256]
    - name: ToTensor
    - name: ToBinaryMask
      threshold: 0.5
model_path: path/to/checkpoint/thyroid/tn3k/ResNet_HSeg/ckp_best.pth
seg_dir: path/to/results/seg/tn3k/ResNet_HSeg
evaluation_metrics:
  seg:
    - name: Dice
    - name: ACC
    - name: mIoU