# train ae or vae
mode: train
model:
  # can be AE, VAE and DDPM
  name: SeM
  # encoder config
  encoder:
    name: SwinU
    image_size: [256, 256]
    in_channel: 1
    out_channel: 1
    patch_channel: 32
    patch_size: 2
    down_channels: [64, 128, 256]
    middle_channels: [512, 512]
    building_block: swin
    normalization: layer
    activation: relu
  ### loss function
  segmentation_losses: 
    - name: Dice
    - name: BCEL
  # some other information related to the model
  # in ddpm, it can be the time steps and so on.
loader:
  dataset: 
    name: ImgSegDataset
    data_suffix: jpg
    data_dir: image
    label_dir: mask
  data_path_list: 
    - /media/wlsdzyzl/DATA/flemme-path/to/datasets/thyroid/tn3k/fold1/
    - /media/wlsdzyzl/DATA/flemme-path/to/datasets/thyroid/tn3k/fold2/
    - /media/wlsdzyzl/DATA/flemme-path/to/datasets/thyroid/tn3k/fold3/
  batch_size: 4
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Resize
      ## the value must be list
      size: [256, 256]
    - name: ToTensor
val_loader:
  dataset: 
    name: ImgSegDataset
    data_suffix: jpg
    data_dir: image
    label_dir: mask
  data_path_list: 
    - /media/wlsdzyzl/DATA/flemme-path/to/datasets/thyroid/tn3k/fold4/
  batch_size: 8
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: Resize
      ## the value must be list
      size: [256, 256]
    - name: ToTensor
    # - name: Normalize
    #   mean: [0.485, 0.456, 0.406]
    #   std: [0.229, 0.224, 0.225]
check_point_dir: /media/wlsdzyzl/DATA/flemme-ckp/thyroid/tn3k/SwinU

### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0003
  weight_decay: 0.00000001
lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
evaluation_metrics:
  seg:
    - name: Dice
    - name: ACC
    - name: mIoU
max_epoch: 500
warmup_epoch: 2
write_after_iters: 2
save_after_epochs: 5