models:
  #### 64 * 64
  - name: SeM
    # encoder config
    encoder:
      name: UNet
      image_size: [64, 64]
      in_channel: 1
      out_channel: 1
      proj_channel: 32
      proj_scaling: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: single
      normalization: batch
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL
  - name: SeM
    # encoder config
    encoder:
      name: SwinU
      image_size: [64, 64]
      in_channel: 1
      out_channel: 1
      patch_channel: 32
      patch_size: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: swin
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL
  - name: SeM
    # encoder config
    encoder:
      name: VMambaU
      image_size: [64, 64]
      in_channel: 1
      out_channel: 1
      patch_channel: 32
      patch_size: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: vmamba
      scan_mode: single
      flip_scan: false
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL

  - name: SeM
    # encoder config
    encoder:
      name: UNet
      image_size: [64, 64]
      in_channel: 1
      out_channel: 1
      proj_channel: 32
      proj_scaling: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: single
      normalization: batch
      num_block: 4
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL
  - name: SeM
    # encoder config
    encoder:
      name: SwinU
      image_size: [64, 64]
      in_channel: 1
      out_channel: 1
      patch_channel: 32
      patch_size: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: swin
      num_block: 4
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL
  ##### 128 * 128
  - name: SeM
    # encoder config
    encoder:
      name: VMambaU
      image_size: [64, 64]
      in_channel: 1
      out_channel: 1
      patch_channel: 32
      patch_size: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: vmamba
      scan_mode: single
      flip_scan: false
      num_block: 4
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL


  - name: SeM
    # encoder config
    encoder:
      name: UNet
      image_size: [128, 128]
      in_channel: 1
      out_channel: 1
      proj_channel: 32
      proj_scaling: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: single
      normalization: batch
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL
  - name: SeM
    # encoder config
    encoder:
      name: SwinU
      image_size: [128, 128]
      in_channel: 1
      out_channel: 1
      patch_channel: 32
      patch_size: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: swin
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL
  ##### 128 * 128
  - name: SeM
    # encoder config
    encoder:
      name: VMambaU
      image_size: [128, 128]
      in_channel: 1
      out_channel: 1
      patch_channel: 32
      patch_size: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: vmamba
      scan_mode: single
      flip_scan: false
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL

  - name: SeM
    # encoder config
    encoder:
      name: UNet
      image_size: [128, 128]
      in_channel: 1
      out_channel: 1
      proj_channel: 32
      proj_scaling: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: single
      normalization: batch
      num_block: 4
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL
  - name: SeM
    # encoder config
    encoder:
      name: SwinU
      image_size: [128, 128]
      in_channel: 1
      out_channel: 1
      patch_channel: 32
      patch_size: 2
      num_block: 4
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: swin
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL
  ##### 128 * 128
  - name: SeM
    # encoder config
    encoder:
      name: VMambaU
      image_size: [128, 128]
      in_channel: 1
      out_channel: 1
      patch_channel: 32
      patch_size: 2
      num_block: 4
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: vmamba
      scan_mode: single
      flip_scan: false
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL



  - name: SeM
    # encoder config
    encoder:
      name: UNet
      image_size: [64, 64, 64]
      in_channel: 1
      out_channel: 1
      proj_channel: 32
      proj_scaling: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: single
      normalization: batch
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL
  - name: SeM
    # encoder config
    encoder:
      name: SwinU
      image_size: [64, 64, 64]
      in_channel: 1
      out_channel: 1
      patch_channel: 32
      patch_size: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: swin
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL
  ##### 64 * 64 * 64
  - name: SeM
    # encoder config
    encoder:
      name: VMambaU
      image_size: [64, 64, 64]
      in_channel: 1
      out_channel: 1
      patch_channel: 32
      patch_size: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: vmamba
      scan_mode: single
      flip_scan: false
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL


  - name: SeM
    # encoder config
    encoder:
      name: UNet
      image_size: [64, 64, 64]
      in_channel: 1
      out_channel: 1
      proj_channel: 32
      proj_scaling: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: single
      normalization: batch
      num_block: 4
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL
  - name: SeM
    # encoder config
    encoder:
      name: SwinU
      image_size: [64, 64, 64]
      in_channel: 1
      out_channel: 1
      patch_channel: 32
      patch_size: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: swin
      num_block: 4
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL
  ##### 64 * 64 * 64
  - name: SeM
    # encoder config
    encoder:
      name: VMambaU
      image_size: [64, 64, 64]
      in_channel: 1
      out_channel: 1
      patch_channel: 32
      patch_size: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: vmamba
      scan_mode: single
      flip_scan: false
      num_block: 4
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL

  #### 128 * 128 * 128
  - name: SeM
    # encoder config
    encoder:
      name: UNet
      image_size: [128, 128, 128]
      in_channel: 1
      out_channel: 1
      proj_channel: 32
      proj_scaling: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: single
      normalization: batch
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL
  - name: SeM
    # encoder config
    encoder:
      name: SwinU
      image_size: [128, 128, 128]
      in_channel: 1
      out_channel: 1
      patch_channel: 32
      patch_size: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: swin
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL
  - name: SeM
    # encoder config
    encoder:
      name: VMambaU
      image_size: [128, 128, 128]
      in_channel: 1
      out_channel: 1
      patch_channel: 32
      patch_size: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: vmamba
      scan_mode: single
      flip_scan: false
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL

  ##### 128 * 128 * 128
  - name: SeM
    # encoder config
    encoder:
      name: UNet
      image_size: [128, 128, 128]
      in_channel: 1
      out_channel: 1
      proj_channel: 32
      proj_scaling: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: single
      normalization: batch
      num_block: 4
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL
  - name: SeM
    # encoder config
    encoder:
      name: SwinU
      image_size: [128, 128, 128]
      in_channel: 1
      out_channel: 1
      patch_channel: 32
      patch_size: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: swin
      num_block: 4
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL
  - name: SeM
    # encoder config
    encoder:
      name: VMambaU
      image_size: [128, 128, 128]
      in_channel: 1
      out_channel: 1
      patch_channel: 32
      patch_size: 2
      down_channels: [64, 128]
      middle_channels: [256, 256]
      building_block: vmamba
      scan_mode: single
      flip_scan: false
      num_block: 4
    ### loss function
    segmentation_losses: 
      - name: Dice
      - name: BCEL