# train ae or vae
mode: test
determinstic: true
model:
  # can be AE, VAE and DDPM
  name: SeM
  # encoder config
  encoder:
    name: UNet
    image_size: [64, 128, 128]
    in_channel: 1
    out_channel: 1
    patch_size: 2
    down_channels: [64, 128]
    middle_channels: [256, 256]
    building_block: single
    normalization: batch
  ### loss function
  segmentation_losses: 
    - name: Dice
    - name: BCEL
  # some other information related to the model
  # in ddpm, it can be the time steps and so on.
loader:
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/img/Task06_Lung/fold_test
    # - /media/wlsdzyzl/DATA1/datasets/img/Task06_Lung/fold2
    # - /media/wlsdzyzl/DATA1/datasets/img/Task06_Lung/fold3 
  dataset: 
    name: PatchImgSegDataset
    dim: 3
    data_suffix: .nii.gz
    data_dir: imagesTr
    label_dir: labelsTr
    lazy_loading: True
    slice_builder:
      name: SliceBuilder
      patch_shape: [64, 128, 128]
      stride_shape: [64, 128, 128]
  batch_size: 8
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: ToTensor

model_path: /media/wlsdzyzl/DATA1/flemme-ckp/ImageCAS/UNet_Patch/ckp_last.pth

seg_dir: /media/wlsdzyzl/DATA1/flemme-results/UNet/task06lung
save_target: true
save_input: true
save_colorized: true

evaluation_metrics:
  seg:
    - name: Dice
    - name: ACC
    - name: mIoU
