# train ae or vae
mode: train
model:
  # can be AE, VAE and DDPM
  name: SeM
  # encoder config
  encoder:
    name: UNet
    image_size: [64, 128, 128]
    in_channel: 1
    out_channel: 1
    patch_size: 2
    down_channels: [64, 128]
    middle_channels: [256, 256]
    building_block: single
    normalization: batch
  ### loss function
  segmentation_losses: 
    - name: Dice
    - name: BCEL
  # some other information related to the model
  # in ddpm, it can be the time steps and so on.
loader:
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/img/Task06_Lung/fold1
    - /media/wlsdzyzl/DATA1/datasets/img/Task06_Lung/fold2
    - /media/wlsdzyzl/DATA1/datasets/img/Task06_Lung/fold3 
  dataset: 
    name: PatchImgSegDataset
    dim: 3
    data_suffix: .nii.gz
    data_dir: imagesTr
    label_dir: labelsTr
    lazy_loading: True
    slice_builder:
      name: FilterSliceBuilder
      patch_shape: [64, 128, 128]
      stride_shape: [32, 64, 64]
      threshold: 0.01
      slack_acceptance: 0.01
  batch_size: 2
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: ToTensor
val_loader:
  dataset:
    name: PatchImgSegDataset
    dim: 3
    data_suffix: .nii.gz
    data_dir: imagesTr
    label_dir: labelsTr
    lazy_loading: True
    slice_builder:
      name: FilterSliceBuilder
      patch_shape: [64, 128, 128]
      stride_shape: [32, 64, 64]
      threshold: 0.01
      slack_acceptance: 0.01
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/img/Task06_Lung/fold4  
  batch_size: 2
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: ToTensor
check_point_dir: /media/wlsdzyzl/DATA1/flemme-ckp/ImageCAS/UNet_Patch

### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0003
  weight_decay: 0.00000001

lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
evaluation_metrics:
  seg:
    - name: Dice
    - name: ACC
    - name: mIoU
max_epoch: 100
warmup_epochs: 1
write_after_iters: 10
save_after_epochs: 2