# train ae or vae
#### a template for pcd encoder
mode: test
model:
  # can be AE, VAE, SeM and DDPM
  name: ClM
  # encoder config
  encoder:
    name: CNN
    image_size: [40, 136, 120]
    in_channel: 1
    out_channel: 18
    patch_size: 2
    down_channels: [64, 128]
    middle_channels: [256, 256]
    building_block: single
    normalization: group
    dense_channels: [512, 512]
  classification_losses: 
    - name: CE
loader:
  dataset: 
    name: ImgClsDataset
    dim: 3
    data_dir: train/imagesTr
    data_suffix: .nii.gz
    crop_nonzero:
      margin: [2,2,2]
    cls_label: 
      Dataset101_MSDliver: 1
      Dataset102_MSDpancreas: 2
      Dataset103_MSDvessel: 3
      Dataset104_MSDspleen: 4  
      Dataset105_MSDcolon: 5
      Dataset110_THORheart: 6
      Dataset111_THORaorta: 7
      Dataset112_THORtrachea: 8
      Dataset113_THOResophagus: 9    
      Dataset120_TOSliver: 10
      Dataset121_TOSlung: 11
      Dataset122_TOSpancreas: 12 
      Dataset123_TOSspleen: 13
      Dataset124_TOScolon: 14
      Dataset125_TOSheart: 15
      Dataset126_TOSaorta: 16
      Dataset127_TOStrachea: 17
      Dataset128_TOSesophagus: 18
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/img/aaai_clients
  batch_size: 64
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Resize
      size: [40, 136, 120]
    - name: ToTensor
  class_label_transforms:
    - name: ToOneHot
      num_classes: 19
      ignore_background: True
    - name: ToTensor
model_path: /media/wlsdzyzl/DATA1/flemme-ckp/aaai_clients/CNN_CLM/ckp_best_score.pth
pickle_results: true
pickle_path: /media/wlsdzyzl/DATA1/flemme-pickled
evaluation_metrics:
  cls:
    - name: ACC
tsne_visualization: 
  top_n: -1
  title: t-SNE Visualization
  vis_dim: 2
  perplexity: 30
  label_names:       
    - Dataset101_MSDliver
    - Dataset102_MSDpancreas
    - Dataset103_MSDvessel
    - Dataset104_MSDspleen
    - Dataset105_MSDcolon
    - Dataset110_THORheart
    - Dataset111_THORaorta
    - Dataset112_THORtrachea
    - Dataset113_THOResophagus  
    - Dataset120_TOSliver
    - Dataset121_TOSlung
    - Dataset122_TOSpancreas
    - Dataset123_TOSspleen
    - Dataset124_TOScolon
    - Dataset125_TOSheart
    - Dataset126_TOSaorta
    - Dataset127_TOStrachea
    - Dataset128_TOSesophagus
