# train ae or vae
#### a template for pcd encoder
mode: train
model:
  # can be AE, VAE, SeM and DDPM
  name: ClM
  # encoder config
  encoder:
    name: CNN
    image_size: [40, 136, 120]
    in_channel: 1
    out_channel: 18
    patch_size: 2
    down_channels: [64, 128]
    middle_channels: [256, 256]
    building_block: single
    normalization: group
    dense_channels: [512, 512]
  classification_losses: 
    - name: CE
loader:
  dataset: 
    name: ImgClsDataset
    dim: 3
    data_dir: train/imagesTr
    data_suffix: .nii.gz
    crop_nonzero:
      margin: [2,2,2]
    cls_label: 
      Dataset101_MSDliver: 1
      Dataset102_MSDpancreas: 2
      Dataset103_MSDvessel: 3
      Dataset104_MSDspleen: 4  
      Dataset105_MSDcolon: 5
      Dataset110_THORheart: 6
      Dataset111_THORaorta: 7
      Dataset112_THORtrachea: 8
      Dataset113_THOResophagus: 9    
      Dataset120_TOSliver: 10
      Dataset121_TOSlung: 11
      Dataset122_TOSpancreas: 12 
      Dataset123_TOSspleen: 13
      Dataset124_TOScolon: 14
      Dataset125_TOSheart: 15
      Dataset126_TOSaorta: 16
      Dataset127_TOStrachea: 17
      Dataset128_TOSesophagus: 18
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/img/aaai_clients
  batch_size: 16
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Resize
      size: [40, 136, 120]
    - name: ToTensor
  class_label_transforms:
    - name: Relabel
      offset: -1
    - name: ToOneHot
      num_classes: 18
    - name: ToTensor
check_point_dir: /media/wlsdzyzl/DATA/flemme-ckp/aaai_clients/CNN_CLM
resume: false
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.00000001
evaluation_metrics:
  cls:
    - name: ACC
score_metric:
  name: ACC
### scheduler for learning rate
lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
max_epoch: 100
write_after_iters: 5
save_after_epochs: 2
