# train ae or vae
#### a template for pcd encoder
mode: train
model:
  # can be AE, VAE, SeM and DDPM
  name: AE
  # encoder config
  encoder:
    name: PointTrans
    in_channel: 3
    point_num: 1024
    building_block: pct_oa
    num_neighbors_k: 20
    folding_times: 2
    local_feature_channels: [64, 64, 128, 256, 512]
    dense_channels: [1024]
    decoder_dense_channels: [512, 256]
    activation: lrelu
    normalization: group
    vector_embedding: True
  reconstruction_losses: 
    - name: EMD
      eps: 0.005
      iters: 50
loader:
  dataset: 
    name: PcdDataset
    data_dir: 02691156/points
    data_suffix: .pts
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/pcd/shapenetcore_v0  
  batch_size: 2
  num_workers: 8
  shuffle: true
  drop_last: true
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 1024
    - name: ToTensor
      dtype: float
check_point_dir: /media/wlsdzyzl/DATA/flemme-ckp/SHAPENET/02691156/PointTrans_AE_EMD
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.00000001
### scheduler for learning rate
lr_scheduler: 
  name: ReduceLROnPlateau
  patience: 5
max_epoch: 500
write_after_iters: 50
write_sample_num: 4
save_after_epochs: 10