# train ae or vae
#### a template for pcd encoder
mode: train
model:
  # can be AE, VAE, SeM and DDPM
  name: VAE
  # encoder config
  encoder:
    name: SeqTrans
    in_channel: 3
    point_num: 256
    building_block: pct_sa
    # num_neighbors_k: 20
    seq_feature_channels: [512, 512, 512, 512, 512, 512]
    num_heads: 8
    d_k: 64
    voxel_resolutions: [0, 0, 16, 16, 0, 0]
    activation: gelu
    normalization: layer
    # name: PointTrans
    # in_channel: 3
    # point_num: 256
    # building_block: dense
    # # num_neighbors_k: 20
    # local_feature_channels: [512, 512, 512, 512, 512, 512]
    # dense_channels: [512]
    # activation: gelu
    # normalization: layer
    channel_attention: eca
    # vector_embedding: false
  reconstruction_losses: 
    - name: CD
  distribution_loss:
    name: KL
    weight: 0.0001
loader:
  dataset: 
    name: PcdDataset
    data_dir: left
    data_suffix: ply
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/pcd/imageCAS/lrply/mask/
  batch_size: 2
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      method: qfps
      num: 2560
    - name: ToTensor
check_point_dir: /media/wlsdzyzl/DATA1/flemme-ckp/imagecas/left/SeqTrans_VAE
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.00000001
### scheduler for learning rate
lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
sampler:
  name: NormalSampler
max_epoch: 100
write_after_iters: 50
write_sample_num: 4
save_after_epochs: 10