# train ae or vae
#### a template for pcd encoder
mode: train
model:
  # can be AE, VAE, SeM and DDPM
  name: DDPM
  num_steps: 1000
  beta_schedule: consine
  eps_model:
    time_channel: 128
    encoder:
      name: PointTrans
      in_channel: 3
      point_num: 256
      building_block: pct_oa
      num_neighbors_k: 20
      local_feature_channels: [128, 256, 512, 1024]
      dense_channels: [1024]
      activation: lrelu
      normalization: group
      channel_attention: eca
      vector_embedding: false
      time_injection: cross_atten
    decoder:
      name: PointNet
      dense_channels: [512, 256, 128]
  eps_loss:
    name: MSE
loader:
  dataset: 
    name: PcdDataset
    data_dir: skeleton
    data_suffix: ply
  data_path_list: 
    - /media/wlsdzyzl/DATA1/vcg-results/skeleton/imagecas_clean/sknet_pointtrans
  batch_size: 16
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      method: qfps
      num: 256
    - name: ToTensor
check_point_dir: /media/wlsdzyzl/DATA1/flemme-ckp/imagecas_clean/PointTrans_Diffusion_Skeleton
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.00000001
### scheduler for learning rate
lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
sampler:
  name: NormalSampler
max_epoch: 1000
write_after_iters: 10
write_sample_num: 4
save_after_epochs: 10