mode: test
model:
  # can be AE, VAE, SeM and DDPM
  name: AE
  # encoder config
  encoder:
    name: PointNet
    in_channel: 3
    point_num: 1024
    building_block: dense
    num_neighbors_k: 20
    local_feature_channels: [64, 64, 128, 256, 512]
    dense_channels: [1024]
    decoder_dense_channels: [512, 256]
    activation: lrelu
    normalization: group
    vector_embedding: True
    ## for decoder
    folding_times: 2
    base_shape: 
      type: grid
      width: 1.0
      height: 1.0
      # radius: 0.15
  reconstruction_losses: 
    - name: EMD
      eps: 0.005
      iters: 50

loader:
  dataset: 
    name: PCDDataset
    data_dir: 02691156/points
    data_suffix: .pts
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/shapenetcore_v0  
  batch_size: 32
  num_workers: 8
  shuffle: true
  drop_last: true
  data_transforms:
    - name: Normalize
      method: mean
    - name: FixedPoints
      num: 1024
    - name: ToTensor
      dtype: float

model_path: path/to/checkpoint/SHAPENET/02691156/PointNet/PointNet_AE_EMD_LOCALK_FOLDING/ckp_best_loss.pth
#### directory that saves the reconstructed images
recon_dir: path/to/results/recon/shapenet/ae_pointnet_folding

#### metrics used for evaluation (reconstruction accuracy)
evaluation_metrics:
  recon:
    - name: EMD
    - name: CD