mode: test
model:
  # can be AE, VAE and DDPM
  name: SeM
  # encoder config
  encoder:
    name: PointNet
    in_channel: 3
    ### segmentation label
    out_channel: 4
    point_num: 2048
    building_block: single
    conv_channels: [64, 64, 128, 256, 512]
    fc_channels: [1024]
    decoder_fc_channels: [512, 256]
    activation: lrelu
    pointwise: True

loader:
  dataset: 
    name: PCDSegDataset
    data_dir: points
    label_dir: points_label
    data_suffix: .pts
    label_suffix: .seg
  data_path_list: 
    - path/to/datasets/shapenetcore_v0/03001627 
  batch_size: 8
  num_workers: 8
  shuffle: true
  drop_last: true
  data_transforms:
    - name: MinMaxNormalize
    - name: FixedPoints
      num: 2048
    - name: ToTensor
      dtype: float
  label_transforms:
    - name: FixedPoints
      num: 2048
    - name: ToOneHot
      num_classes: 5
      ignore_background: true
    - name: ToTensor
      dtype: float

model_path: path/to/checkpoint/SHAPENET/03001627/PointNet_Seg/ckp_last.pth
#### directory that saves the reconstructed images
seg_dir: path/to/results/seg/shapenet/03001627/pointnet
save_colorized: true
save_target: true
#### metrics used for evaluation (reconstruction accuracy)
evaluation_metrics:
  seg:
    - name: Dice
    - name: ACC
    - name: mIoU
