# train ae or vae
#### a template for pcd encoder
mode: train
# pretrained: /media/wlsdzyzl/DATA1/flemme-ckp/SHAPENET/02691156/PointNet_DDPM/ckp_last.pth
model:
  # can be AE, VAE and DDPM
  name: DDPM
  num_steps: 1000
  beta_schedule: consine
  eps_model:
    time_channel: 128
    encoder:
      name: PointNet
      in_channel: 3
      out_channel: 3
      point_num: 2048
      building_block: dense
      conv_channels: [64, 64, 128, 256, 512]
      dense_channels: [1024]
      decoder_dense_channels: [512, 256]
      activation: lrelu
      vector_embedding: False
  eps_loss:
    name: MSE
loader:
  dataset: 
    name: PcdDataset
    data_dir: 02691156/points
    data_suffix: .pts
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/pcd/shapenetcore_v0  
  batch_size: 64
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: MinMaxNormalize
    - name: FixedPoints
      num: 2048
    - name: ToTensor
      dtype: float
check_point_dir: /media/wlsdzyzl/DATA1/flemme-ckp/SHAPENET/02691156/PointNet_DDPM
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.00000001
### scheduler for learning rate
# lr_scheduler: 
#   name: ReduceLROnPlateau
#   patience: 5
lr_scheduler: 
  name: OneCycleLR
# sampler:
#   name: NormalSampler
#   end_step: 200
#   rand_seed: 2024
#   clipped: true
#   clip_range: [0.0, 1.0]
max_epoch: 5000
write_after_iters: 20
save_after_epochs: 10