# train ae or vae
#### a template for pcd encoder
mode: train
model:
  # can be AE, VAE, SeM and DDPM
  name: VAE
  # encoder config
  encoder:
    name: PointNet2
    in_channel: 3
    out_channel: 3
    point_num: 1024
    building_block: dense
    num_neighbors_k: 32
    num_fps_points: [512, 256, 128]
    fps_feature_channels: [128, 256, 512]
    neighbor_radius: [0.1, 0.2, 0.4]
    dense_channels: [1024]
    activation: relu
    normalization: batch
    vector_embedding: true
  decoder:
    name: PointNet
    # folding_times: 2
  reconstruction_losses: 
    - name: Chamfer
  distribution_loss:
    name: KL
    weight: 0.0001
loader:
  dataset: 
    name: PcdDataset
    data_dir: 02691156/points
    data_suffix: .pts
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/pcd/shapenetcore_v0  
  batch_size: 32
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 1024
    - name: ToTensor
      dtype: float
check_point_dir: /media/wlsdzyzl/DATA1/flemme-ckp/SHAPENET/02691156/PointNet/PointNet2_VAE_Chamfer
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.00000001
### scheduler for learning rate
lr_scheduler: 
  name: ReduceLROnPlateau
  patience: 5
sampler:
  name: NormalSampler
max_epoch: 500
write_after_iters: 20
save_after_epochs: 10