# train ae or vae
#### a template for pcd encoder
mode: train
model:
  # can be AE, VAE, SeM and DDPM
  name: VAE
  # encoder config
  encoder:
    name: PointNet
    in_channel: 3
    point_num: 1024
    building_block: dense
    num_neighbors_k: 20
    local_feature_channels: [64, 64, 128, 256, 512]
    dense_channels: [1024]
    decoder_dense_channels: [512, 256]
    activation: lrelu
    normalization: group
    vector_embedding: True
  reconstruction_losses: 
    - name: EMD
  distribution_loss:
    name: KL
    weight: 0.1
loader:
  dataset: 
    name: PCDDataset
    data_dir: 02691156/points
    data_suffix: .pts
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/pcd/shapenetcore_v0  
  batch_size: 32
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 1024
    - name: ToTensor
      dtype: float
check_point_dir: path/to/checkpoint/SHAPENET/02691156/PointNet/PointNet_VAE_EMD_LOCAL_K
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.00000001
### scheduler for learning rate
lr_scheduler: 
  name: ReduceLROnPlateau
  patience: 5
sampler:
max_epoch: 500
write_after_iters: 20
save_after_epochs: 10