# train ae or vae
#### a template for pcd encoder
mode: train
model:
  # can be AE, VAE and DDPM
  name: SeM
  # encoder config
  encoder:
    name: PointNet2
    in_channel: 3
    out_channel: 4
    point_num: 2048
    building_block: dense
    num_neighbors_k: 32
    num_fps_points: [1024, 512, 256, 64]
    fps_feature_channels: [128, 256, 512, 1024]
    neighbor_radius: [0.1, 0.2, 0.4, 0.8]
    dense_channels: [1024]
    activation: relu
    normalization: batch
    final_concat: true
    vector_embedding: False
  ### loss function
  # loss_reduction: sum
  segmentation_losses:
    - name: Dice
      normalization: softmax
    - name: CE
loader:
  dataset: 
    name: PcdSegDataset
    data_dir: points
    label_dir: points_label
    data_suffix: .pts
    label_suffix: .seg
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/pcd/shapenetcore_v0/segmentation/Airplane/
  batch_size: 8
  num_workers: 8
  shuffle: true
  drop_last: true
  data_transforms:
    - name: MinMaxNormalize
    - name: FixedPoints
      num: 2048
    - name: ToTensor
  label_transforms:
    - name: FixedPoints
      num: 2048
    - name: Relabel
      offset: -1
    - name: ToOneHot
      num_classes: 4
    - name: ToTensor
check_point_dir: /media/wlsdzyzl/DATA1/flemme-ckp/SHAPENET/Airplane/PointNet2_Seg
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.00000001
### scheduler for learning rate
lr_scheduler: 
  name: ReduceLROnPlateau
  patience: 50
evaluation_metrics:
  seg:
    - name: Dice
    - name: ACC
    - name: mIoU
max_epoch: 100
write_after_iters: 20
save_after_epochs: 5