# train ae or vae
#### a template for pcd encoder
mode: test
determinstic: True
model:
  # can be AE, VAE, SeM and DDPM
  name: AE
  # encoder config
  encoder:
    name: PointTrans2
    in_channel: 3
    out_channel: 3
    point_num: 2048
    building_block: pct_oa_non_ffn
    # num_neighbors_k: 20
    num_neighbors_k: 32
    num_fps_points: [2048, 1024, 512, 256, 128]
    neighbor_radius: [0.1, 0.2, 0.4, 0.6, 0.8]
    fps_feature_channels: [64, 64, 128, 256, 512]
    decoder_dense_channels: [512, 512, 256, 256, 128]
    dense_channels: [1024]
    activation: lrelu
    normalization: group
    vector_embedding: True
    # pos_embedding: True
    # long_range_modeling: True
  decoder:
    name: PointNet
    folding_times: 2
  is_supervised: True
  condition_embedding:
    combine_condition: injection
    condition_injection: gate_bias
    encoder:
      name: OneHot
      type: categories
      out_channel: 128
      num_classes: 46
    decoder: same_as_encoder
  reconstruction_losses: 
    - name: DCD
      alpha: 40
      n_lambda: 0.5
    - name: CD
      weight: 0.001
loader:
  dataset: 
    name: PcdReconWithClassLabelDataset
    data_dir: partial
    target_dir: target
    data_suffix: .ply
    target_suffix: .ply
    cls_label: MedPointS
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/pcd/MedPointS/completion/fold5
  batch_size: 64
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 2048
    - name: ToTensor
  target_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 2048
    - name: ToTensor
  class_label_transforms:
    - name: Relabel
      offset: -1
    - name: ToOneHot
      num_classes: 46
    - name: ToTensor

model_path: /media/wlsdzyzl/DATA/flemme-ckp/MedPointS/PointTrans2/PointTrans2_CPL/ckp_best_loss.pth
recon_dir: /media/wlsdzyzl/DATA/flemme-results/cpl/medshapenet/PointTrans2/
save_input: true
save_target: true
evaluation_metrics:
  recon:
    - name: CD
    # - name: EMD