# train ae or vae
#### a template for pcd encoder
mode: test
model:
  # can be AE, VAE, SeM and DDPM
  name: ClM
  # encoder config
  encoder:
    name: PointMamba2
    in_channel: 3
    out_channel: 46
    point_num: 2048
    building_block: pmamba
    num_neighbors_k: 32
    num_fps_points: [1024, 512, 256, 128, 64]
    fps_feature_channels: [64, 64, 128, 256, 512]
    neighbor_radius: [0.1, 0.2, 0.4, 0.6, 0.8]
    dense_channels: [1024, 512, 256]
    activation: lrelu
    normalization: group
    long_range_modeling: True
    # scan_strategies: [z_order, center_dist]
    scan_strategies: [x_order, y_order, z_order, center_dist]
    sorted_query: True
    flip_scan: True
    pos_embedding: True
  classification_losses: 
    - name: CE
loader:
  dataset: 
    name: PcdClsDataset
    data_suffix: .ply
    cls_label: MedPointS
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/pcd/MedPointS/classification/fold5
  batch_size: 32
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 2048
    - name: ToTensor
  class_label_transforms:
    - name: Relabel
      offset: -1
    - name: ToOneHot
      num_classes: 46
    - name: ToTensor
model_path: /media/wlsdzyzl/DATA/flemme-ckp/MedPointS/PointMamba2/PointMamba2_FULL_CLS/ckp_best_score.pth


evaluation_metrics:
  cls:
    - name: ACC
tsne_visualization: 
  top_n: 10
  title: t-SNE Visualization of Top-10 Classes
  vis_dim: 2
  label_names: medshapenet