# train ae or vae
#### a template for pcd encoder
mode: test
model:
  # can be AE, VAE, SeM and DDPM
  name: ClM
  # encoder config
  encoder:
    name: PointNet
    in_channel: 3
    out_channel: 46
    point_num: 2048
    building_block: dense
    # num_neighbors_k: 20
    local_feature_channels: [64, 64, 128, 256, 512]
    dense_channels: [1024, 512, 256]
    activation: lrelu
    normalization: group
  classification_losses: 
    - name: CE
loader:
  dataset: 
    name: PcdClsDataset
    data_suffix: .ply
    cls_label: MedPointS
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/pcd/MedPointS/classification/fold1
    - /media/wlsdzyzl/DATA1/datasets/pcd/MedPointS/classification/fold2
    - /media/wlsdzyzl/DATA1/datasets/pcd/MedPointS/classification/fold3
    - /media/wlsdzyzl/DATA1/datasets/pcd/MedPointS/classification/fold4
  batch_size: 32
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 2048
    - name: ToTensor
      dtype: float
  class_label_transforms:
    - name: ToOneHot
      num_classes: 47
      ignore_background: true
    - name: ToTensor
      dtype: float
model_path: /media/wlsdzyzl/DATA1/flemme-ckp/MedPointS/PointNet/PointNet_CLS/ckp_last.pth
# eval_batch_num: 8
pickle_results: true
pickle_path: /media/wlsdzyzl/DATA1/flemme-pickled
evaluation_metrics:
  cls:
    - name: ACC
tsne_visualization: 
  top_n: 10
  title: t-SNE Visualization of Top-10 Classes
  vis_dim: 2
  size: 10
  alpha: 0.5
  perplexity: 30
  label_names: MedPointS