# train ae or vae
#### a template for pcd encoder
mode: test
model:
  # can be AE, VAE, SeM and DDPM
  name: ClM
  # encoder config
  encoder:
    name: PointNet
    in_channel: 3
    out_channel: 46
    point_num: 2048
    building_block: dense
    # num_neighbors_k: 20
    local_feature_channels: [64, 64, 128, 256, 512]
    dense_channels: [1024, 512, 256]
    activation: lrelu
    normalization: group
  classification_losses: 
    - name: CE
loader:
  dataset: 
    name: PcdClsDataset
    data_suffix: .ply
    cls_label: MedPointS
  data_path_list: 
    - /data/guoqingzhang/datasets/MedPointS/classification/fold5
  batch_size: 32
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 2048
    - name: ToTensor
  class_label_transforms:
    - name: Relabel
      offset: -1
    - name: ToOneHot
      num_classes: 46
    - name: ToTensor
model_path: /data/guoqingzhang/flemme-ckp/MedPointS/PointNet/PointNet_CLS/ckp_last.pth
# eval_batch_num: 8
pickle_results: true
pickle_path: /media/wlsdzyzl/DATA/flemme-pickled
# load_pickle_results: true
evaluation_metrics:
  cls:
    - name: ACC
tsne_visualization: 
  top_n: 10
  title: t-SNE Visualization of Top-10 Classes
  vis_dim: 2
  size: 10
  alpha: 0.5
  color_map: jet
  one_to_multiple: 5
  noise_level: 0.06
  perplexity: 30
  label_names: MedPointS
  tsne_path: ./tsne.png