# train ae or vae
#### a template for pcd encoder
mode: train
model:
  # can be AE, VAE, SeM and DDPM
  name: ClM
  # encoder config
  encoder:
    name: PointTrans2
    in_channel: 3
    out_channel: 46
    point_num: 2048
    building_block: pct_oa
    # num_neighbors_k: 20
    # local_feature_channels: [64, 64, 128, 256, 512]
    num_neighbors_k: 32
    num_fps_points: [1024, 512, 256, 128, 64]
    fps_feature_channels: [64, 64, 128, 256, 512]
    neighbor_radius: [0.1, 0.2, 0.4, 0.6, 0.8]
    dense_channels: [1024, 512, 256]
    activation: lrelu
    normalization: group
    # pos_embedding: True
    # long_range_modeling: True
  classification_losses: 
    - name: CE
loader:
  dataset: 
    name: PcdClsDataset
    data_suffix: .ply
    cls_label: MedPointS
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/pcd/MedPointS/classification/fold1
    - /media/wlsdzyzl/DATA/datasets/pcd/MedPointS/classification/fold2
    - /media/wlsdzyzl/DATA/datasets/pcd/MedPointS/classification/fold3
  batch_size: 64
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 2048
    - name: ToTensor
  class_label_transforms:
    - name: Relabel
      offset: -1
    - name: ToOneHot
      num_classes: 46
    - name: ToTensor
val_loader:
  dataset: 
    name: PcdClsDataset
    data_suffix: .ply
    cls_label: MedPointS
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/pcd/MedPointS/classification/fold4
  batch_size: 32
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      num: 2048
    - name: ToTensor
  class_label_transforms:
    - name: Relabel
      offset: -1
    - name: ToOneHot
      num_classes: 46
    - name: ToTensor
check_point_dir: /media/wlsdzyzl/DATA/flemme-ckp/MedPointS/PointTrans2/PointTrans2_CLS
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.00000001
evaluation_metrics:
  cls:
    - name: ACC
score_metric:
  name: ACC
### scheduler for learning rate
lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
max_epoch: 100
write_after_iters: 20
save_after_epochs: 1
