# train ae or vae
mode: train
model:
  # can be AE, VAE and DDPM
  name: HSeM
  # encoder config
  encoder:
    name: SwinU
    image_size: [96, 192, 192]
    in_channel: 1
    out_channel: 1
    patch_size: 2
    down_channels: [64, 128]
    middle_channels: [256, 256]
    building_block: swin
    normalization: layer
    window_size: [4, 8, 8]
  ### loss function
  segmentation_losses: 
    - name: Dice
    - name: BCEL
  # some other information related to the model
  # in ddpm, it can be the time steps and so on.
loader:
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/biomed_3d_dataset/ImageCAS/fold1
    - /media/wlsdzyzl/DATA1/datasets/biomed_3d_dataset/ImageCAS/fold2
    - /media/wlsdzyzl/DATA1/datasets/biomed_3d_dataset/ImageCAS/fold3 
  dataset: 
    name: ImgSegDataset
    dim: 3
    data_suffix: .nii.gz
  batch_size: 2
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Resize
      size: [96, 192, 192]
    - name: ToTensor
val_loader:
  dataset: 
    name: ImgSegDataset
    dim: 3
    data_suffix: .nii.gz
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/biomed_3d_dataset/ImageCAS/fold4  
  batch_size: 2
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: Resize
      size: [96, 192, 192]
    - name: ToTensor
check_point_dir: /media/wlsdzyzl/DATA1/flemme-ckp/ImageCAS/SwinU_HSeg

### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0003
  weight_decay: 0.00000001

lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
evaluation_metrics:
  seg:
    - name: Dice
    - name: ACC
    - name: mIoU
max_epoch: 500
warmup_epochs: 2
write_after_iters: 2
save_after_epochs: 5