# train ae or vae
mode: test
model:
  # can be AE, VAE and DDPM
  name: SeM
  # encoder config
  encoder:
    name: UNet
    image_size: [64, 128, 64]
    in_channel: 4
    out_channel: 4
    patch_size: 2
    down_channels: [64, 128]
    middle_channels: [256, 256]
    building_block: single
    normalization: batch
  ### loss function
  segmentation_losses: 
    - name: Dice
      normalization: softmax
    - name: CE
  # some other information related to the model
  # in ddpm, it can be the time steps and so on.
loader:
  dataset: 
    name: MultiModalityPatchImgSegDataset
    dim: 3
    data_dir: [flair, t1, t1ce, t2]
    data_suffix: [flair.nii.gz, t1.nii.gz, t1ce.nii.gz, t2.nii.gz]
    label_dir: seg
    label_suffix: seg.nii.gz
    data_combine: cat
    crop_nonzero:
      margin: [2,2,2]
      crop_by: raw
    lazy_loading: True
    slice_builder:
      name: SliceBuilder
      patch_shape: [64, 128, 64]
      stride_shape: [48, 96, 48]
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/img/BraTS2021/fold5
  batch_size: 8
  num_workers: 8
  shuffle: False
  data_transforms:
    - name: ToTensor
  label_transforms:
    - name: Relabel
      map: 
        - [4, 3]
    - name: ToOneHot
      num_classes: 4
    - name: ToTensor

model_path: /media/wlsdzyzl/DATA1/flemme-ckp/BRATS21/UNet-Patch/ckp_last.pth
seg_dir: /media/wlsdzyzl/DATA1/flemme-results/UNet-Patch/BRATS21
save_target: true
save_input: true
save_colorized: true
pickle_results: true
pickle_path: /media/wlsdzyzl/DATA1/flemme-pickled
evaluation_metrics:
  seg:
    - name: Dice
    - name: ACC
    - name: mIoU
