# train ae or vae
mode: train
model:
  # can be AE, VAE and DDPM
  name: SeM
  # encoder config
  encoder:
    name: UNet
    image_size: [64, 128, 64]
    in_channel: 4
    out_channel: 4
    patch_size: 2
    down_channels: [64, 128]
    middle_channels: [256, 256]
    building_block: single
    normalization: batch
  ### loss function
  segmentation_losses: 
    - name: Dice
      normalization: softmax
    - name: CE
  # some other information related to the model
  # in ddpm, it can be the time steps and so on.
loader:
  dataset: 
    name: MultiModalityPatchImgSegDataset
    dim: 3
    data_dir: [flair, t1, t1ce, t2]
    data_suffix: [flair.nii.gz, t1.nii.gz, t1ce.nii.gz, t2.nii.gz]
    label_dir: seg
    label_suffix: seg.nii.gz
    data_combine: cat
    crop_nonzero:
      margin: [2,2,2]
      crop_by: raw
    lazy_loading: True
    slice_builder:
      name: FilterSliceBuilder
      patch_shape: [64, 128, 64]
      stride_shape: [32, 64, 32]
      threshold: 0.01
      slack_acceptance: 0.01
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/img/BraTS2021/fold1
    - /media/wlsdzyzl/DATA1/datasets/img/BraTS2021/fold2
    - /media/wlsdzyzl/DATA1/datasets/img/BraTS2021/fold3
  batch_size: 8
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: ToTensor
  label_transforms:
    - name: Relabel
      map: 
        - [4, 3]
    - name: ToOneHot
      num_classes: 4
      ignore_background: False
    - name: ToTensor

val_loader:
  dataset: 
    name: MultiModalityPatchImgSegDataset
    dim: 3
    data_dir: [flair, t1, t1ce, t2]
    data_suffix: [flair.nii.gz, t1.nii.gz, t1ce.nii.gz, t2.nii.gz]
    label_dir: seg
    label_suffix: seg.nii.gz
    data_combine: cat
    crop_nonzero:
      margin: [2,2,2]
      crop_by: raw
    lazy_loading: True
    slice_builder:
      name: FilterSliceBuilder
      patch_shape: [64, 128, 64]
      stride_shape: [32, 64, 32]
      threshold: 0.01
      slack_acceptance: 0.01
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/img/BraTS2021/fold4
  batch_size: 2
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: ToTensor
  label_transforms:
    - name: Relabel
      map: 
        - [4, 3]
    - name: ToOneHot
      num_classes: 4
      ignore_background: False
    - name: ToTensor
check_point_dir: /media/wlsdzyzl/DATA1/flemme-ckp/BRATS21/UNet-Patch
resume: true
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0003
  weight_decay: 0.00000001

lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
evaluation_metrics:
  seg:
    - name: Dice
    - name: ACC
    - name: mIoU
max_epoch: 20
warmup_epochs: 1
write_after_iters: 100
save_after_epochs: 1