# train ae or vae
mode: train
model:
  # can be AE, VAE and DDPM
  name: SeM
  # encoder config
  encoder:
    name: CNN
    image_size: [120, 192, 120]
    in_channel: 4
    out_channel: 4
    patch_size: 2
    down_channels: [64, 128]
    middle_channels: [256, 256]
    building_block: res
    num_blocks: 1
    normalization: batch
  ### loss function
  segmentation_losses: 
    - name: Dice
      normalization: softmax
    - name: CE
  # some other information related to the model
  # in ddpm, it can be the time steps and so on.
loader:
  dataset: 
    name: MultiModalityImgSegDataset
    dim: 3
    data_dir: [flair, t1, t1ce, t2]
    data_suffix: [flair.nii.gz, t1.nii.gz, t1ce.nii.gz, t2.nii.gz]
    label_dir: seg
    label_suffix: seg.nii.gz
    data_combine: cat
    crop_nonzero:
      margin: [2,2,2]
      crop_by: raw
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/biomed_3d_dataset/BraTS2021/fold1
    - /media/wlsdzyzl/DATA/datasets/biomed_3d_dataset/BraTS2021/fold2
    - /media/wlsdzyzl/DATA/datasets/biomed_3d_dataset/BraTS2021/fold3
  batch_size: 2
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Resize
      size: [120, 192, 120]
    - name: ToTensor
  label_transforms:
    - name: Resize
      size: [120, 192, 120]
    - name: Relabel
      map: 
        - [4, 3]
    - name: ToOneHot
      num_classes: 4
    - name: ToTensor

val_loader:
  dataset: 
    name: MultiModalityImgSegDataset
    dim: 3
    data_dir: [flair, t1, t1ce, t2]
    data_suffix: [flair.nii.gz, t1.nii.gz, t1ce.nii.gz, t2.nii.gz]
    label_dir: seg
    label_suffix: seg.nii.gz
    data_combine: cat
    crop_nonzero:
      margin: [2,2,2]
      crop_by: raw
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/biomed_3d_dataset/BraTS2021/fold4
  batch_size: 2
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: Resize
      size: [120, 192, 120]
    - name: ToTensor
  label_transforms:
    - name: Resize
      size: [120, 192, 120]
    - name: Relabel
      map: 
        - [4, 3]
    - name: ToOneHot
      num_classes: 4
    - name: ToTensor
check_point_dir: /media/wlsdzyzl/DATA/flemme-ckp/BRATS21/ResNet

### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0003
  weight_decay: 0.00000001

lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
evaluation_metrics:
  seg:
    - name: Dice
    - name: ACC
    - name: mIoU
max_epoch: 500
warmup_epochs: 2
write_after_iters: 5
save_after_epochs: 2