## generated by chatgpt
import numpy as np
import matplotlib.pyplot as plt
from flemme.color_table import scannet_color_table, custom_color_table

def draw_color_bar(
    color_table,
    title,
    ax,
    index_fontsize=6,
    rotate_xticks=True,
):
    """
    Draw a horizontal color bar from a (N, 3) color table.

    Args:
        color_table (np.ndarray): shape (N, 3), values in [0, 1]
        title (str): title shown above the color bar
        ax (matplotlib axis): axis to draw on
        index_fontsize (int): fontsize of index labels
        rotate_xticks (bool): whether to rotate x tick labels
    """
    assert color_table.ndim == 2 and color_table.shape[1] == 3
    assert np.max(color_table) <= 1.0 and np.min(color_table) >= 0.0

    # Draw color bar
    ax.imshow([color_table], aspect="auto")
    ax.set_title(title)

    # Remove y axis
    ax.set_yticks([])

    # Index labels
    n = len(color_table)
    ax.set_xticks(range(n))
    ax.set_xticklabels(
        range(n),
        fontsize=index_fontsize,
        rotation=90 if rotate_xticks else 0,
    )


def draw_combined_color_bars(
    color_tables,
    titles,
    figsize=(14, 3),
    save_path="color_bars.png",
):
    """
    Draw multiple color tables stacked vertically.

    Args:
        color_tables (list[np.ndarray])
        titles (list[str])
        figsize (tuple)
        save_path (str)
    """
    assert len(color_tables) == len(titles)

    fig, axes = plt.subplots(
        len(color_tables),
        1,
        figsize=figsize,
        gridspec_kw={"height_ratios": [1] * len(color_tables)},
    )

    if len(color_tables) == 1:
        axes = [axes]

    for ax, table, title in zip(axes, color_tables, titles):
        draw_color_bar(
            color_table=table,
            title=title,
            ax=ax,
        )

    plt.tight_layout()
    fig.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.close(fig)

    print(f"Saved to {save_path}")

if __name__ == "__main__":

    draw_combined_color_bars(
        color_tables=[scannet_color_table, custom_color_table],
        titles=["ScanNet Color Table", "Custom Color Table"],
        figsize=(14, 3),
        save_path="../images/color_bars.png",
    )
