# train ae or vae
mode: test
model:
  # can be AE, VAE and DDPM
  name: HSeM
  # encoder config
  encoder:
    name: UNet
    image_size: [384, 256]
    in_channel: 3
    out_channel: 1
    patch_channel: 32
    patch_size: 2
    down_channels: [64, 128, 256]
    up_attens: [null, null, atten]
    middle_channels: [512, 512]
    building_block: single
    normalization: batch
  ### loss function
  segmentation_losses: 
    - name: Dice
    - name: BCEL
  # some other information related to the model
  # in ddpm, it can be the time steps and so on.
loader:
  dataset: 
    name: ImgSegDataset
    data_dir: image
    label_dir: mask
    data_suffix: jpg
    label_suffix: png
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/ISIC/fold5/
  batch_size: 2
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: Resize
      ## the value must be list
      size: [384, 256]
    - name: ToTensor

model_path: /media/wlsdzyzl/DATA/flemme-ckp/ISIC/UNet_Atten_HSeg/ckp_best_loss.pth
seg_dir: /media/wlsdzyzl/DATA/flemme-results/seg/ISIC/UNet_Atten_HSeg
evaluation_metrics:
  seg:
    - name: Dice
    - name: ACC
    - name: mIoU
