# train ae or vae
determinstic: true
mode: test
model:
  # can be AE, VAE and DDPM
  name: SeM
  # encoder config
  encoder:
    name: UNet
    image_size: [384, 256]
    in_channel: 3
    out_channel: 1
    patch_channel: 32
    patch_size: 2
    down_channels: [64, 128, 256]
    middle_channels: [512, 512]
    building_block: single
    normalization: batch
  ### loss function
  segmentation_losses: 
    - name: Dice
    - name: BCEL
  # some other information related to the model
  # in ddpm, it can be the time steps and so on.
loader:
  dataset: 
    name: ImgSegDataset
    data_dir: image
    label_dir: mask
    data_suffix: jpg
    label_suffix: png
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/img/ISIC/fold5/
  batch_size: 16
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: ToTensor
    - name: Resize
      ## the value must be list
      size: [384, 256]

model_path: /media/wlsdzyzl/DATA1/flemme-ckp/ISIC/UNet/ckp_best_loss.pth
seg_dir: /media/wlsdzyzl/DATA1/flemme-results/seg/ISIC/UNet
pickle_results: true
# pickle_path:  /media/wlsdzyzl/DATA1/flemme-pickled
save_target: true
save_input: true
save_colorized: true
evaluation_metrics:
  seg:
    - name: Dice
    - name: ACC
    - name: mIoU
