# train ae or vae
mode: test
rand_seed: 2024
model:
  # can be AE, VAE and DDPM
  name: DDIM
  num_steps: 1000
  sample_num_steps: 100
  beta_schedule: consine
  eps_model:
    name: Base
    # encoder config
    time_channel: 128
    encoder:
      name: UNet
      image_size: [28, 28]
      in_channel: 1
      patch_size: 1
      down_channels: [32, 64]
      middle_channels: [128, 128]
      ## allow an asummetrical architecture
      # decode_down_channels: [32, 64]
      ### with time embedding
      building_block: single
      activation: silu
      num_blocks: 2
      normalization: group
      num_norm_groups: 16
      dropout: 0.1
      ## the value can be list or int
    # time_injection: bias
    condition_embedding:
      combine_condition: injection
      condition_injection: add_to_time
      encoder:
        name: OneHot
        type: categories
        out_channel: 128
        num_classes: 10
      decoder: same_as_encoder
  # classifier_free_guidance:
  #   condition_dropout: 0.2
  #   guidance_weight: 2.0
      ## allow an asummetrical architecture
      # decoder_dense_channels: [128 256]
  ## 2D ddpm
  eps_loss:
    name: MSE
model_path: /media/wlsdzyzl/DATA1/flemme-ckp/MNIST/CDDPM/ckp_last.pth
loader:
  dataset: 
    name: MNIST
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/img/MNIST
  batch_size: 128
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: ToTensor
    - name: Resize
      ## the value must be list
      size: [28, 28]
    - name: Normalize
      mean: [0.5]
      std: [0.5]
eval_batch_num: 1
recon_dir: /media/wlsdzyzl/DATA1/flemme-results/recon/mnist/cddpm
eval_gen:
  gen_dir: /media/wlsdzyzl/DATA1/flemme-results/gen/mnist/cddpm
  sampler:
    name: NormalSampler
    clipped: true
    clip_range: [-1.0, 1.0]
    num_sample_steps: 1000
  random_sample_num: 100
