mode: train
model:
  # can be AE, VAE and DDPM
  name: VAE
  # encoder config
  encoder:
    name: CNN
    in_channel: 1
    ## the value can be list or int
    image_size: 32
    patch_size: 1
    # usample_function: conv
    # dsample_function: conv
    down_channels: [16, 32]
    middle_channels: [32, 32]
    # up_channels: [16, 8]
    building_block: single
    dense_channels: [128]
    decoder_dense_channels: [64, 32]
  condition_embedding:
    combine_condition: injection
    condition_injection: cross_atten
    encoder:
      name: OneHot
      type: categories
      out_channel: 1
      num_classes: 10
    decoder:
      name: OneHot
      type: categories
      out_channel: 128
      num_classes: 10
  ### loss function
  reconstruction_losses: 
    name: MSE
  distribution_loss:
    name: KL
    weight: 1.0
  # some other information related to the model
  # in ddpm, it can be the time steps and so on.
loader:
  dataset: 
    name: MNIST
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/img/MNIST  
  batch_size: 128
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Resize
      ## the value must be list
      size: [32, 32]
    - name: ToTensor
    - name: Normalize
      mean: [0.1307]
      std: [0.3081]

check_point_dir: /media/wlsdzyzl/DATA1/flemme-ckp/MNIST/CNN_CVAE
resume: True
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0003
  weight_decay: 0.00000001
lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
max_epoch: 100
write_after_iters: 50
save_after_epochs: 5