# train ae or vae
mode: test
model:
  # can be AE, VAE and DDPM
  name: SeM
  # encoder config
  encoder:
    name: UNet
    image_size: [320, 256]
    in_channel: 3
    out_channel: 1
    patch_channel: 32
    patch_size: 2
    down_channels: [64, 128, 256]
    middle_channels: [512, 512]
    building_block: single
    normalization: batch
  ### loss function
  segmentation_losses: 
    - name: Dice
    - name: BCEL
  # some other information related to the model
  # in ddpm, it can be the time steps and so on.
loader:
  dataset: 
    name: ImgSegDataset
    data_dir: images
    label_dir: masks
    data_suffix: jpg
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/img/CVC-ClinicDB/fold5/
  batch_size: 16
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: ToTensor
    - name: Resize
      ## the value must be list
      size: [320, 256]
  label_transforms:
    - name: ToTensor
    - name: Resize
      ## the value must be list
      size: [320, 256]
    - name: ToBinaryMask
      threshold: 0.5
model_path: /media/wlsdzyzl/DATA/flemme-ckp/CVC-ClinicDB/UNet/ckp_best_loss.pth
seg_dir: /media/wlsdzyzl/DATA/flemme-results/seg/CVC-ClinicDB/UNet
save_target: true
save_input: true
save_colorized: true
evaluation_metrics:
  seg:
    - name: Dice
    - name: ACC
    - name: mIoU
