# train ae or vae
mode: test
model:
  # can be AE, VAE and DDPM
  name: HSeM
  # encoder config
  encoder:
    name: SwinU
    image_size: [320, 256]
    in_channel: 3
    out_channel: 1
    patch_channel: 32
    patch_size: 2
    down_channels: [64, 128, 256]
    middle_channels: [512, 512]
    building_block: swin
    window_size: [10, 8]
    activation: relu
  ### loss function
  segmentation_losses: 
    - name: Dice
    - name: BCEL
  # some other information related to the model
  # in ddpm, it can be the time steps and so on.
loader:
  dataset: 
    name: ImgSegDataset
    data_dir: images
    label_dir: masks
    data_suffix: jpg
  data_path_list: 
    - path/to/datasets/CVC-ClinicDB/fold5/
  batch_size: 16
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: Resize
      ## the value must be list
      size: [320, 256]
    - name: ToTensor
  label_transforms:
    - name: Resize
      ## the value must be list
      size: [320, 256]
    - name: ToTensor
    - name: ToBinaryMask
      threshold: 0.5
model_path: path/to/checkpoint/CVC-ClinicDB/SwinU_HSeg/ckp_best.pth
seg_dir: path/to/results/seg/CVC-ClinicDB/SwinU_HSeg
evaluation_metrics:
  seg:
    - name: Dice
    - name: ACC
    - name: mIoU