# train ae or vae
mode: train
model:
  # can be AE, VAE and DDPM
  name: HSeM
  # encoder config
  encoder:
    name: CNN
    image_size: [320, 256]
    in_channel: 3
    out_channel: 1
    patch_channel: 32
    patch_size: 2
    down_channels: [64, 128, 256]
    middle_channels: [512, 512]
    building_block: res
    num_blocks: 1
    normalization: batch
  ### loss function
  segmentation_losses: 
    - name: Dice
    - name: BCEL
  # some other information related to the model
  # in ddpm, it can be the time steps and so on.
loader:
  dataset: 
    name: ImgSegDataset
    data_dir: images
    label_dir: masks
    data_suffix: jpg
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/CVC-ClinicDB/fold1/
    - /media/wlsdzyzl/DATA/datasets/CVC-ClinicDB/fold2/
    - /media/wlsdzyzl/DATA/datasets/CVC-ClinicDB/fold3/
  batch_size: 4
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: ToTensor
    - name: Resize
      ## the value must be list
      size: [320, 256]
val_loader:
  dataset: 
    name: ImgSegDataset
    data_dir: images
    label_dir: masks
    data_suffix: jpg
  data_path_list: 
    - /media/wlsdzyzl/DATA/datasets/CVC-ClinicDB/fold4/
  batch_size: 8
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: ToTensor
    - name: Resize
      ## the value must be list
      size: [320, 256]
check_point_dir: /media/wlsdzyzl/DATA/flemme-ckp/CVC-ClinicDB/ResNet_HSeg

### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0003
  weight_decay: 0.00000001
lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
evaluation_metrics:
  seg:
    - name: Dice
    - name: ACC
    - name: mIoU
max_epoch: 500
warmup_epochs: 2
write_after_iters: 5
save_after_epochs: 2