# train ae or vae
mode: test
model:
  # can be AE, VAE and DDPM
  name: SeM
  # encoder config
  encoder:
    name: VMambaU
    image_size: [128, 128]
    in_channel: 1
    out_channel: 1
    patch_channel: 32
    patch_size: 2
    down_channels: [64, 128, 256]
    middle_channels: [512, 512]
    building_block: vmamba
    normalization: layer
    scan_mode: single
    flip_scan: false
  ### loss function
  segmentation_losses: 
    - name: Dice
    - name: BCEL
loader:
  dataset: 
    name: ImgSegDataset
    data_dir: frames
    label_dir: mask
    data_suffix: png
  data_path_list: 
    - /media/wlsdzyzl/DATA1/datasets/Echonet/fold5/
  batch_size: 16
  num_workers: 8
  shuffle: false
  data_transforms:
    - name: ToTensor
    - name: Resize
      ## the value must be list
      size: [128, 128]
    - name: GrayScale
model_path: /media/wlsdzyzl/DATA1/flemme-ckp/Echonet/MambaU/ckp_best_loss.pth
seg_dir: /media/wlsdzyzl/DATA1/flemme-results/seg/Echonet/MambaU
evaluation_metrics:
  seg:
    - name: Dice
    - name: ACC
    - name: mIoU